### ISSUE TITLE
app.json is not up to date

### ISSUE THREAD

**Issue by lvanvugt** [PacktPublishing/Automated-Testing-in-Microsoft-Dynamics-365-Business-Central#1]
As off BC15 app.json should provide different info:

- "test": "14.0.0.0" is no longer possible and should be replaced by dependencies to relevant library and test apps ([example](https://dev.azure.com/businesscentralapps/HelloWorld/_git/HelloWorld?path=%2Ftest%2Fapp.json))
- runtime should also be provided

**Comment by lvanvugt** [comment]
@deepesh-packt, why did you close this issue? I did put it here as we need to fix this in due time.

**Comment by deepesh-packt** [comment]
@lvanvugt Hey Ivan, did you complete fixing this? If yes, can I please close the issue?
Thanks.

**Comment by lvanvugt** [comment]
No yet. Will do with next version of the book.

**Comment by deepesh-packt** [comment]
Okay, so can we close this issue? As this issue is related to this book. 
Thanks.

**Comment by lvanvugt** [comment]
No, it's a reminder.

**Comment by lvanvugt** [comment]
Being implemented on 2nd edition of the book (and in separate GitHub repo).
