### ISSUE TITLE
BC365 PowerBI integration with Power Automate

### ISSUE THREAD

**Issue by jbrenner85499** [PacktPublishing/Automated-Testing-in-Microsoft-Dynamics-365-Business-Central#3]
When I am viewing a PowerBI report within BC365 SaaS, I have an option to click a Power Automate button within my report to run a flow. In this case, the button is stuck on triggering... When I run the flow within the Microsoft Teams integration of PowerBI, it works as expected.

**Comment by lvanvugt** [comment]
OK, but what does this have tp do with this repo? It appears to me you registered this on the wrong GitHub repo.
